name: Push To Windows VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on:
      - self-hosted
      - windows
      - VM1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to IIS folder
        shell: powershell
        run: |
          $src = "$env:GITHUB_WORKSPACE\*"
          $dst = "C:\inetpub\wwwroot"

          New-Item -Path $dst -ItemType Directory -Force | Out-Null
          Copy-Item -Path $src -Destination $dst -Recurse -Force
